workspace 'MyApp.xcworkspace'

target 'MyLib' do

    platform :ios, '9.3'
    xcodeproj 'MyLib/MyLib.xcodeproj'
    pod 'AFNetworking', '~> 3.0'
    pod 'YYModel'

end


target 'MyApp' do
    
    platform :ios, '9.3'
    xcodeproj 'MyApp/MyApp.xcodeproj'
    pod 'AFNetworking', '~> 3.0'
    pod 'YYModel'
    
end